const PREFIX = 'weather/';

export const LOAD_WEATHER_DATA_REQUEST = `${PREFIX}LOAD_WEATHER_DATA_REQUEST`;
export const LOAD_WEATHER_DATA_SUCCESS = `${PREFIX}LOAD_WEATHER_DATA_SUCCESS`;
export const LOAD_WEATHER_DATA_ERROR = `${PREFIX}LOAD_WEATHER_DATA_ERROR`;
